# Generated by Django 5.2.12 on 2026-03-15 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_business_claim_workflow(apps, schema_editor):
    BusinessClaim = apps.get_model("users", "BusinessClaim")
    BusinessClaimEvent = apps.get_model("users", "BusinessClaimEvent")

    for claim in BusinessClaim.objects.select_related("user", "company"):
        update_fields = []
        if not claim.submitter_first_name and claim.user.first_name:
            claim.submitter_first_name = claim.user.first_name
            update_fields.append("submitter_first_name")
        if not claim.submitter_last_name and claim.user.last_name:
            claim.submitter_last_name = claim.user.last_name
            update_fields.append("submitter_last_name")
        if update_fields:
            claim.save(update_fields=update_fields)

        if not BusinessClaimEvent.objects.filter(claim=claim).exists():
            BusinessClaimEvent.objects.create(
                claim=claim,
                actor=claim.user,
                event_type="submitted",
                metadata={
                    "intent": claim.intent,
                    "company_name": claim.company.name if claim.company else claim.business_name,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_backfill_personal_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclaim',
            name='decision_reason_code',
            field=models.CharField(blank=True, choices=[('insufficient_connection', 'We could not confirm your connection to the business'), ('missing_company_match', 'We need a clearer match to the company profile'), ('missing_contact_details', 'We need more business contact details'), ('incomplete_submission', 'The verification submission is incomplete'), ('other', 'Other')], max_length=40),
        ),
        migrations.AddField(
            model_name='businessclaim',
            name='intent',
            field=models.CharField(choices=[('existing', 'Claim existing business'), ('new', 'Add new business')], default='existing', max_length=20),
        ),
        migrations.AddField(
            model_name='businessclaim',
            name='resubmission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessclaim',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessclaim',
            name='review_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='businessclaim',
            name='submitter_first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='businessclaim',
            name='submitter_last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='BusinessClaimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_claim_events', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='users.businessclaim')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.RunPython(backfill_business_claim_workflow, migrations.RunPython.noop),
    ]
